{
 "title": "Total IP scans",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total malicious scans",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \n    total_scans, \n    total_malicious_scans, \n    malicious_percentage \nFROM \n    v_grafana_malicious_stats \nWHERE \n    $__timeFilter(last_scan);"
    }
   ]
  },
  {
   "title": "Total positive flags per day",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \n    time_sec, \n    total_scans_per_day, \n    total_positives_per_day \nFROM \n    v_grafana_daily_trends \nWHERE \n    $__timeFilter(scan_date)\nORDER BY \n    time_sec ASC;"
    }
   ]
  },
  {
   "title": "Total scans per day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "threat_indicators",
     "rawSql": "SELECT\n    time_sec,\n    total_scans_per_day,\n    total_positives_per_day\nFROM\n    cyber_intelligence.v_grafana_daily_trends\nWHERE\n    $__timeFilter(scan_date)\nORDER BY\n    time_sec ASC;"
    }
   ]
  }
 ]
}