{
 "title": "Virus total scans",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total malicious scans",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\n    -- Total number of all scans\n    COUNT(id) AS total_scans,\n    \n    -- Total number of scans where positives > 0\n    SUM(CASE WHEN threat_score > 0 THEN 1 ELSE 0 END) AS total_malicious_scans,\n    \n    -- Calculate the percentage of malicious scans\n    (SUM(CASE WHEN threat_score > 0 THEN 1 ELSE 0 END) / COUNT(id)) * 100 AS malicious_percentage\nFROM\n    cyber_intelligence.threat_indicators\nWHERE\n    $__timeFilter(last_scan);"
    }
   ]
  },
  {
   "title": "Total positive flags per day",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT\n    -- Calculate the start of the day in UNIX timestamp format\n    UNIX_TIMESTAMP(DATE(last_scan)) AS time_sec,\n    \n    -- Count the number of positive scans (Malicious Scans)\n    SUM(threat_score) AS total_positive\nFROM\n    cyber_intelligence.threat_indicators\nWHERE\n    -- Grafana time range filter\n    $__timeFilter(last_scan)\nGROUP BY\n    time_sec\nORDER BY\n    time_sec ASC;"
    }
   ]
  },
  {
   "title": "Total scans per day",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "virus_total",
     "rawSql": "SELECT\n    UNIX_TIMESTAMP(DATE(last_scan)) AS time_sec,\n    COUNT(id) AS total_scans_per_day,\n    SUM(threat_score) AS total_positives_per_day\nFROM\n    cyber_intelligence.threat_indicators\nWHERE\n    $__timeFilter(last_scan) \nGROUP BY\n    time_sec\nORDER BY\n    time_sec ASC;"
    }
   ]
  }
 ]
}