-- ============================================
-- Cyber Intelligence Database Deployment — POSTGRES
-- Version: 1.1
-- ============================================
-- Runs against: postgres_db (pgvector/pgvector:pg16 + pg_cron, see
-- Dockerfile.postgres). Executed by playbook 04_3_db_postgres.yml as the
-- `postgres` superuser, connected to the `cyber_intelligence` database.
-- Fully idempotent — re-run on every deployment.
--
-- DEPLOYMENT MODEL:
--   This script does NOT create the database itself. `cyber_intelligence`
--   is created by the Postgres container on first init (POSTGRES_DB in
--   docker-compose-cyber-sentinel.yml, service postgres_db).
--
-- SCHEMA:
--   Everything lives in the dedicated `cyber_sentinel` schema instead of
--   `public`, because this Postgres instance may later host unrelated
--   applications and `public` is shared by every database user.
--   `ALTER ROLE ... SET search_path = cyber_sentinel, public` (Section 1)
--   keeps unqualified queries from the app role (log_processor.py, n8n,
--   ad-hoc pgAdmin) working. All DDL below is fully schema-qualified.
--
-- SCHEMA VERSIONING:
--   Plain, idempotent SQL files under config/postgres/, run in order by
--   playbook 04.3: this file, db_partitioning_retention.sql,
--   db_ai_pipeline.sql (then db_ai_config_editor.sql by playbook 04.5).
--
-- IDENTITY COLUMNS:
--   GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so data can be loaded
--   with explicit ids (restores, migrations).
--
-- PARTITIONING:
--   Postgres declarative partitioning must be declared at CREATE TABLE
--   time. dns_queries, network_events and threat_indicators are created
--   here as `PARTITION BY RANGE (...)` parents with NO partitions
--   attached. Partitions and the pg_cron retention jobs are created by
--   db_partitioning_retention.sql, which MUST run immediately after this
--   file — until then every INSERT into those tables is rejected.
--
-- FOREIGN KEYS:
--   A partitioned table can only be an FK TARGET when the referencing
--   columns match its full partition-key unique constraint. Outgoing
--   FKs from a partitioned table to a normal table are fine:
--     - threat_indicators.analysis_result_id -> ai_analysis_results(id)  REAL FK
--     - threat_indicators.type_id            -> dic_indicator_types(id)  REAL FK
--     - threat_indicators.dns_query_id       -> dns_queries(id)          app-layer only
--       (dns_queries is itself partitioned)
--
-- CREDENTIALS:
--   {{ postgres_user }} / {{ vault_postgres_password }} are the app role
--   used by n8n and dns_log_processor (all_servers.yml / encrypted
--   vault.yml), rendered by Ansible's template module.
-- ============================================

-- ============================================
-- SECTION 0: EXTENSIONS
-- ============================================

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- SECTION 1: SCHEMA + USER MANAGEMENT
-- ============================================

CREATE SCHEMA IF NOT EXISTS cyber_sentinel AUTHORIZATION postgres;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '{{ postgres_user }}') THEN
CREATE ROLE "{{ postgres_user }}" LOGIN PASSWORD '{{ vault_postgres_password }}';
ELSE
        ALTER ROLE "{{ postgres_user }}" WITH PASSWORD '{{ vault_postgres_password }}';
END IF;
END
$$;

GRANT CONNECT ON DATABASE cyber_intelligence TO "{{ postgres_user }}";
GRANT USAGE, CREATE ON SCHEMA cyber_sentinel TO "{{ postgres_user }}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cyber_sentinel TO "{{ postgres_user }}";
ALTER DEFAULT PRIVILEGES IN SCHEMA cyber_sentinel GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "{{ postgres_user }}";

-- Convenience, not a correctness requirement: lets already-shipped
-- unqualified queries (log_processor.py, ad-hoc pgAdmin queries) keep
-- working without prefixing every table with `cyber_sentinel.`.
ALTER ROLE "{{ postgres_user }}" SET search_path = cyber_sentinel, public;

-- ============================================
-- SECTION 2: DICTIONARY TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS cyber_sentinel.dic_indicator_types (
                                                                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                  name VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX IF NOT EXISTS idx_name ON cyber_sentinel.dic_indicator_types (name);

INSERT INTO cyber_sentinel.dic_indicator_types (name) VALUES
                                                          ('FQDN'), ('IP'), ('HASH')
    ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS cyber_sentinel.dic_source_providers (
                                                                   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                   name VARCHAR(50) NOT NULL UNIQUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX IF NOT EXISTS idx_name_providers ON cyber_sentinel.dic_source_providers (name);
CREATE INDEX IF NOT EXISTS idx_active ON cyber_sentinel.dic_source_providers (is_active);

INSERT INTO cyber_sentinel.dic_source_providers (name) VALUES
                                                           ('VirusTotal'), ('Abuse_ThreatFox'), ('Abuse_URLhaus'), ('urlscan.io')
    ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS cyber_sentinel.dic_threat_levels (
                                                                score INT PRIMARY KEY,
                                                                description VARCHAR(100) NOT NULL,
    is_malicious_flag BOOLEAN DEFAULT FALSE,
    action_recommended VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

INSERT INTO cyber_sentinel.dic_threat_levels (score, description, is_malicious_flag, action_recommended) VALUES
                                                                                                             (1, 'Clean / Trusted infrastructure',            FALSE, 'Allow'),
                                                                                                             (2, 'Low Risk / Monitor',                        FALSE, 'Monitor'),
                                                                                                             (3, 'Suspicious - manual review needed',         FALSE, 'Review'),
                                                                                                             (4, 'Malicious - confirmed threat',              TRUE,  'Block'),
                                                                                                             (5, 'Critical - active threat, immediate alert', TRUE,  'Block + Alert')
    ON CONFLICT (score) DO NOTHING;

-- ============================================
-- SECTION 3: RAW CTI PAYLOADS (JSONB, one row per provider response)
-- ============================================

CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_data_raw (
                                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                              resource TEXT,
                                                              source_provider TEXT,
                                                              scan_date TIMESTAMP,
                                                              raw_data JSONB NOT NULL,
                                                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_raw_resource_scan ON cyber_sentinel.threat_data_raw (resource, scan_date DESC);
CREATE INDEX IF NOT EXISTS idx_raw_source_provider ON cyber_sentinel.threat_data_raw (source_provider);
CREATE INDEX IF NOT EXISTS idx_raw_data_gin ON cyber_sentinel.threat_data_raw USING GIN (raw_data);

-- ============================================
-- SECTION 4: CORE DATA TABLES
-- ============================================

CREATE TABLE IF NOT EXISTS cyber_sentinel.dns_queries (
                                                          id INT GENERATED BY DEFAULT AS IDENTITY,
                                                          timestamp TIMESTAMP NOT NULL,
                                                          query_type VARCHAR(10) NOT NULL,
    record_type VARCHAR(10),
    domain TEXT NOT NULL,
    source_ip VARCHAR(45) NOT NULL,
    response_ip VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, timestamp)
    ) PARTITION BY RANGE (timestamp);

CREATE INDEX IF NOT EXISTS idx_id_dns ON cyber_sentinel.dns_queries (id);
CREATE INDEX IF NOT EXISTS idx_domain ON cyber_sentinel.dns_queries (domain);
CREATE INDEX IF NOT EXISTS idx_timestamp_dns ON cyber_sentinel.dns_queries (timestamp);
CREATE INDEX IF NOT EXISTS idx_source_ip_dns ON cyber_sentinel.dns_queries (source_ip);
CREATE INDEX IF NOT EXISTS idx_response_ip ON cyber_sentinel.dns_queries (response_ip);
CREATE INDEX IF NOT EXISTS idx_domain_timestamp ON cyber_sentinel.dns_queries (domain, timestamp);

CREATE TABLE IF NOT EXISTS cyber_sentinel.ai_analysis_results (
                                                                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                  threat_score INT NOT NULL,
                                                                  threat_label VARCHAR(50),
    verdict_summary_en TEXT,
    analysis_pl TEXT,
    confidence_score DECIMAL(5,2) DEFAULT NULL,
    analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_threat_level_results
    FOREIGN KEY (threat_score)
    REFERENCES cyber_sentinel.dic_threat_levels(score)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    );
CREATE INDEX IF NOT EXISTS idx_threat_score ON cyber_sentinel.ai_analysis_results (threat_score);
CREATE INDEX IF NOT EXISTS idx_analyzed_at ON cyber_sentinel.ai_analysis_results (analyzed_at);

CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicators (
                                                                id INT GENERATED BY DEFAULT AS IDENTITY,
                                                                dns_query_id INT NOT NULL,
                                                                type_id INT NOT NULL,
                                                                analysis_result_id INT NOT NULL,
                                                                last_scan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                scan_count INT DEFAULT 1,
                                                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                                PRIMARY KEY (id, last_scan),
    CONSTRAINT uk_dns_analysis_scan UNIQUE (dns_query_id, analysis_result_id, last_scan),
    CONSTRAINT fk_indicator_type
    FOREIGN KEY (type_id)
    REFERENCES cyber_sentinel.dic_indicator_types(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT fk_indicator_analysis_result
    FOREIGN KEY (analysis_result_id)
    REFERENCES cyber_sentinel.ai_analysis_results(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
    ) PARTITION BY RANGE (last_scan);

CREATE INDEX IF NOT EXISTS idx_id_ti ON cyber_sentinel.threat_indicators (id);
CREATE INDEX IF NOT EXISTS idx_dns_query ON cyber_sentinel.threat_indicators (dns_query_id);
CREATE INDEX IF NOT EXISTS idx_last_scan ON cyber_sentinel.threat_indicators (last_scan);
CREATE INDEX IF NOT EXISTS idx_type ON cyber_sentinel.threat_indicators (type_id);
CREATE INDEX IF NOT EXISTS idx_analysis_result ON cyber_sentinel.threat_indicators (analysis_result_id);

CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicator_details (
                                                                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                       indicator_id INT NOT NULL,
                                                                       source_id INT NOT NULL,
                                                                       raw_data_id BIGINT,
                                                                       raw_response_hash VARCHAR(64),
    fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_source
    FOREIGN KEY (source_id)
    REFERENCES cyber_sentinel.dic_source_providers(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT fk_raw_data
    FOREIGN KEY (raw_data_id)
    REFERENCES cyber_sentinel.threat_data_raw(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    CONSTRAINT uk_indicator_source UNIQUE (indicator_id, source_id)
    );
CREATE INDEX IF NOT EXISTS idx_indicator ON cyber_sentinel.threat_indicator_details (indicator_id);
CREATE INDEX IF NOT EXISTS idx_source ON cyber_sentinel.threat_indicator_details (source_id);
CREATE INDEX IF NOT EXISTS idx_raw_data_id ON cyber_sentinel.threat_indicator_details (raw_data_id);

CREATE TABLE IF NOT EXISTS cyber_sentinel.network_events (
                                                             id INT GENERATED BY DEFAULT AS IDENTITY,
                                                             timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             dns_query_id INT NULL,
                                                             threat_indicator_id INT NULL,

                                                             source_ip VARCHAR(45) NOT NULL,
    dest_ip VARCHAR(45) NOT NULL,
    dest_port INT,
    protocol VARCHAR(10),
    application_protocol VARCHAR(20),

    request_url TEXT,
    user_agent TEXT,
    http_method VARCHAR(10),

    event_type VARCHAR(50),
    severity INT,
    signature_name VARCHAR(255),
    action_taken VARCHAR(20),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id, timestamp)
    ) PARTITION BY RANGE (timestamp);

CREATE INDEX IF NOT EXISTS idx_id_ne ON cyber_sentinel.network_events (id);
CREATE INDEX IF NOT EXISTS idx_timestamp_ne ON cyber_sentinel.network_events (timestamp);
CREATE INDEX IF NOT EXISTS idx_source_ip_ne ON cyber_sentinel.network_events (source_ip);
CREATE INDEX IF NOT EXISTS idx_dest_ip ON cyber_sentinel.network_events (dest_ip);
CREATE INDEX IF NOT EXISTS idx_severity ON cyber_sentinel.network_events (severity);
CREATE INDEX IF NOT EXISTS idx_event_type ON cyber_sentinel.network_events (event_type);
CREATE INDEX IF NOT EXISTS idx_dns_query_ne ON cyber_sentinel.network_events (dns_query_id);
CREATE INDEX IF NOT EXISTS idx_threat_indicator ON cyber_sentinel.network_events (threat_indicator_id);

-- ============================================
-- SECTION 5: VIEWS FOR ANALYSIS & REPORTING
-- ============================================

CREATE OR REPLACE VIEW cyber_sentinel.v_pending_analysis AS
SELECT
    dq.id AS dns_query_id,
    dq.source_ip,
    dq.domain AS fqdn,
    STRING_AGG(DISTINCT dq.response_ip, ', ' ORDER BY dq.response_ip) AS observable_ip,
    MIN(dq.timestamp) AS first_seen,
    COUNT(DISTINCT dq.id) AS query_count
FROM cyber_sentinel.dns_queries dq
         LEFT JOIN cyber_sentinel.threat_indicators ti ON dq.id = ti.dns_query_id
WHERE ti.id IS NULL
  AND dq.response_ip ~ '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
GROUP BY dq.id, dq.source_ip, dq.domain;

CREATE OR REPLACE VIEW cyber_sentinel.v_latest_threat_reports AS
SELECT
    ti.id,
    ti.dns_query_id,
    ti.type_id,
    ti.analysis_result_id,
    ti.last_scan,
    ti.scan_count,
    ar.threat_score,
    ar.threat_label,
    ar.verdict_summary_en,
    ar.analysis_pl,
    ar.confidence_score
FROM cyber_sentinel.threat_indicators ti
         JOIN cyber_sentinel.ai_analysis_results ar ON ti.analysis_result_id = ar.id
         INNER JOIN (
    SELECT dns_query_id, MAX(last_scan) AS max_scan
    FROM cyber_sentinel.threat_indicators
    GROUP BY dns_query_id
) latest ON ti.dns_query_id = latest.dns_query_id AND ti.last_scan = latest.max_scan;

-- ============================================
-- SECTION 6: GRAFANA VIEWS
-- ============================================

CREATE OR REPLACE VIEW cyber_sentinel.v_grafana_malicious_stats AS
SELECT
    COUNT(vlt.id) AS total_scans,
    SUM(CASE WHEN tl.is_malicious_flag THEN 1 ELSE 0 END) AS total_malicious_scans,
    ROUND((SUM(CASE WHEN tl.is_malicious_flag THEN 1 ELSE 0 END)::numeric / NULLIF(COUNT(vlt.id), 0)) * 100, 2) AS malicious_percentage,
    MAX(vlt.last_scan) AS last_scan,
    MIN(vlt.last_scan) AS first_scan
FROM cyber_sentinel.v_latest_threat_reports vlt
         JOIN cyber_sentinel.dic_threat_levels tl ON vlt.threat_score = tl.score;

CREATE OR REPLACE VIEW cyber_sentinel.v_grafana_daily_trends AS
SELECT
    vlt.last_scan::date AS scan_date,
    EXTRACT(EPOCH FROM date_trunc('day', MAX(vlt.last_scan)))::bigint AS time_sec,
    COUNT(vlt.id) AS total_scans_per_day,
    SUM(CASE WHEN tl.is_malicious_flag THEN 1 ELSE 0 END) AS total_positives_per_day,
    SUM(CASE WHEN NOT tl.is_malicious_flag THEN 1 ELSE 0 END) AS total_clean_per_day,
    MAX(vlt.threat_score) AS max_threat_score_that_day,
    AVG(vlt.threat_score) AS avg_threat_score
FROM cyber_sentinel.v_latest_threat_reports vlt
         JOIN cyber_sentinel.dic_threat_levels tl ON vlt.threat_score = tl.score
GROUP BY scan_date
ORDER BY scan_date DESC;

CREATE OR REPLACE VIEW cyber_sentinel.v_grafana_dns_hourly_traffic AS
SELECT
    date_trunc('hour', timestamp) AS hour_group,
    EXTRACT(EPOCH FROM date_trunc('hour', timestamp))::bigint AS time_sec,
    COUNT(id) AS total_queries,
    COUNT(DISTINCT domain) AS unique_domains,
    COUNT(DISTINCT source_ip) AS unique_sources,
    MAX(timestamp) AS latest_query
FROM cyber_sentinel.dns_queries
GROUP BY hour_group
ORDER BY hour_group DESC;

CREATE OR REPLACE VIEW cyber_sentinel.v_grafana_threat_explorer AS
SELECT
    ne.timestamp,
    dq.domain AS fqdn,
    ne.source_ip,
    ne.dest_ip,
    ne.request_url,
    ne.event_type,
    (SELECT STRING_AGG(sp.name, ', ')
     FROM cyber_sentinel.threat_indicator_details tid
              JOIN cyber_sentinel.dic_source_providers sp ON tid.source_id = sp.id
     WHERE tid.indicator_id = ti.id) AS providers,
    tl.description AS threat_label,
    tl.action_recommended,
    ar.threat_score,
    ne.action_taken
FROM cyber_sentinel.network_events ne
         JOIN cyber_sentinel.dns_queries dq ON ne.dns_query_id = dq.id
         JOIN cyber_sentinel.threat_indicators ti ON ne.threat_indicator_id = ti.id
         JOIN cyber_sentinel.ai_analysis_results ar ON ti.analysis_result_id = ar.id
         JOIN cyber_sentinel.dic_threat_levels tl ON ar.threat_score = tl.score
WHERE tl.is_malicious_flag = TRUE
ORDER BY ne.timestamp DESC;

CREATE OR REPLACE VIEW cyber_sentinel.v_grafana_threat_alerts AS
SELECT
    ti.id AS indicator_id,
    dq.timestamp AS detection_time,
    dq.domain AS fqdn,
    dq.record_type,
    dq.source_ip,
    dq.response_ip AS observable_ip,
    ar.threat_score,
    tl.description AS threat_label,
    tl.is_malicious_flag,
    tl.action_recommended,
    ar.verdict_summary_en AS verdict_en,
    ar.analysis_pl,
    ar.confidence_score,
    ti.scan_count,
    ti.last_scan
FROM cyber_sentinel.threat_indicators ti
         JOIN cyber_sentinel.dns_queries dq ON ti.dns_query_id = dq.id
         JOIN cyber_sentinel.ai_analysis_results ar ON ti.analysis_result_id = ar.id
         JOIN cyber_sentinel.dic_threat_levels tl ON ar.threat_score = tl.score
WHERE tl.is_malicious_flag = TRUE
ORDER BY dq.timestamp DESC, ar.threat_score DESC;

CREATE OR REPLACE VIEW cyber_sentinel.v_threat_scale_for_agent AS
SELECT
    score,
    description,
    is_malicious_flag,
    action_recommended,
    CONCAT(score, ' | ', description, ' (Action: ', action_recommended, ')') AS formatted_line
FROM cyber_sentinel.dic_threat_levels
ORDER BY score ASC;

-- ============================================
-- DEPLOYMENT COMPLETE (schema only)
-- Database: cyber_intelligence, schema: cyber_sentinel
-- NEXT STEP: run db_partitioning_retention.sql — dns_queries, network_events
-- and threat_indicators have ZERO partitions attached until it runs, and
-- will reject every INSERT until then.
-- ============================================