-- ============================================
-- DATA RETENTION STRATEGY — POSTGRES
-- Cyber Intelligence System — Postgres port
-- ============================================
-- Strategy: Monthly declarative partitioning, 6-month retention
-- Tables: cyber_sentinel.dns_queries, cyber_sentinel.network_events,
--         cyber_sentinel.threat_indicators
-- Automation: pg_cron (replaces MySQL Event Scheduler)
--
-- PREREQUISITES:
--   1. Run db_deployment.sql FIRST — the parent tables must already exist
--      in the cyber_sentinel schema as PARTITION BY RANGE tables with zero
--      partitions attached.
--   2. pg_cron extension must be enabled (done in db_deployment.sql,
--      Section 0) with shared_preload_libraries='pg_cron' active on the
--      Postgres container.
--
-- PARTITION NAMING:
--   MySQL partition names were local to each table (p202609 could exist
--   independently on dns_queries, network_events, and threat_indicators).
--   Postgres partitions are ordinary tables in the same schema, so
--   identical names across tables would still collide even within
--   cyber_sentinel. Names here are `<table>_p<YYYYMM>`
--   (e.g. cyber_sentinel.dns_queries_p202609).
--
-- SCHEMA SCOPING:
--   Every pg_class / pg_namespace lookup below filters on
--   n.nspname = 'cyber_sentinel' (or the equivalent join) — this matters
--   now more than it did under `public`, since other future applications
--   may have their own same-named partition maintenance objects in their
--   own schemas, and these functions must never touch them.
-- ============================================

-- ============================================
-- PART 1: MAINTENANCE LOG TABLE (same name/shape as MySQL)
-- ============================================
CREATE TABLE IF NOT EXISTS cyber_sentinel.partition_maintenance_log (
                                                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                        table_name VARCHAR(100) NOT NULL,
    partition_name VARCHAR(100) NOT NULL,
    action VARCHAR(20) NOT NULL,
    error_message TEXT,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX IF NOT EXISTS idx_executed_at ON cyber_sentinel.partition_maintenance_log (executed_at);
CREATE INDEX IF NOT EXISTS idx_table_name_log ON cyber_sentinel.partition_maintenance_log (table_name);

-- ============================================
-- PART 2: INITIAL PARTITIONS
-- ============================================
-- Covers current month + 3 future months, plus a DEFAULT catch-all so no
-- INSERT is ever rejected for lack of a matching partition. Adjust the
-- starting month below to match the actual deployment date if this runs
-- later than expected.

CREATE TABLE IF NOT EXISTS cyber_sentinel.dns_queries_p202609 PARTITION OF cyber_sentinel.dns_queries FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.dns_queries_p202610 PARTITION OF cyber_sentinel.dns_queries FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.dns_queries_p202611 PARTITION OF cyber_sentinel.dns_queries FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.dns_queries_p202612 PARTITION OF cyber_sentinel.dns_queries FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.dns_queries_p_default PARTITION OF cyber_sentinel.dns_queries DEFAULT;

CREATE TABLE IF NOT EXISTS cyber_sentinel.network_events_p202609 PARTITION OF cyber_sentinel.network_events FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.network_events_p202610 PARTITION OF cyber_sentinel.network_events FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.network_events_p202611 PARTITION OF cyber_sentinel.network_events FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.network_events_p202612 PARTITION OF cyber_sentinel.network_events FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.network_events_p_default PARTITION OF cyber_sentinel.network_events DEFAULT;

CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicators_p202609 PARTITION OF cyber_sentinel.threat_indicators FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicators_p202610 PARTITION OF cyber_sentinel.threat_indicators FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicators_p202611 PARTITION OF cyber_sentinel.threat_indicators FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicators_p202612 PARTITION OF cyber_sentinel.threat_indicators FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE IF NOT EXISTS cyber_sentinel.threat_indicators_p_default PARTITION OF cyber_sentinel.threat_indicators DEFAULT;

-- ============================================
-- PART 3: MAINTENANCE FUNCTIONS (same names as MySQL's stored procedures)
-- ============================================
-- Functions themselves live in cyber_sentinel too (not public) — schema-
-- qualified at creation and at every call site (including the pg_cron
-- job commands in Part 4), so they work regardless of whatever role or
-- search_path ends up invoking them.

CREATE OR REPLACE FUNCTION cyber_sentinel.sp_add_future_partitions()
RETURNS void AS $$
DECLARE
v_table_name TEXT;
    v_target_month DATE;
    v_partition_name TEXT;
    v_range_start DATE;
    v_range_end DATE;
    i INT;
BEGIN
    FOREACH v_table_name IN ARRAY ARRAY['dns_queries', 'network_events', 'threat_indicators']
    LOOP
        FOR i IN 1..3 LOOP
            v_target_month := date_trunc('month', CURRENT_DATE) + (i || ' months')::interval;
            v_range_start := v_target_month;
            v_range_end := v_target_month + interval '1 month';
            v_partition_name := v_table_name || '_p' || to_char(v_target_month, 'YYYYMM');

            IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relname = v_partition_name AND n.nspname = 'cyber_sentinel'
            ) THEN
BEGIN
EXECUTE format(
        'CREATE TABLE cyber_sentinel.%I PARTITION OF cyber_sentinel.%I FOR VALUES FROM (%L) TO (%L)',
        v_partition_name, v_table_name, v_range_start, v_range_end
        );
INSERT INTO cyber_sentinel.partition_maintenance_log (table_name, partition_name, action)
VALUES (v_table_name, v_partition_name, 'ADD');
EXCEPTION WHEN OTHERS THEN
                    INSERT INTO cyber_sentinel.partition_maintenance_log (table_name, partition_name, action, error_message)
                    VALUES (v_table_name, v_partition_name, 'ADD_FAILED', SQLERRM);
END;
END IF;
END LOOP;
END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION cyber_sentinel.sp_drop_old_partitions()
RETURNS void AS $$
DECLARE
rec RECORD;
    v_cutoff DATE := date_trunc('month', CURRENT_DATE) - interval '6 months';
    v_partition_month DATE;
    v_yyyymm TEXT;
BEGIN
FOR rec IN
SELECT c.relname AS partition_name, p.relname AS table_name
FROM pg_inherits i
         JOIN pg_class c ON c.oid = i.inhrelid
         JOIN pg_class p ON p.oid = i.inhparent
         JOIN pg_namespace n ON n.oid = p.relnamespace
WHERE n.nspname = 'cyber_sentinel'
  AND p.relname IN ('dns_queries', 'network_events', 'threat_indicators')
  AND c.relname ~ '_p[0-9]{6}$'
    LOOP
        v_yyyymm := right(rec.partition_name, 6);
v_partition_month := to_date(v_yyyymm, 'YYYYMM');

        IF v_partition_month < v_cutoff THEN
BEGIN
                -- Non-concurrent DETACH: acceptable here since this runs
                -- during the scheduled low-traffic maintenance window
                -- (02:00, same as MySQL). CONCURRENTLY cannot be used
                -- inside a plpgsql function (it cannot run in a transaction
                -- block).
EXECUTE format('ALTER TABLE cyber_sentinel.%I DETACH PARTITION cyber_sentinel.%I', rec.table_name, rec.partition_name);
EXECUTE format('DROP TABLE cyber_sentinel.%I', rec.partition_name);
INSERT INTO cyber_sentinel.partition_maintenance_log (table_name, partition_name, action)
VALUES (rec.table_name, rec.partition_name, 'DROP');
EXCEPTION WHEN OTHERS THEN
                INSERT INTO cyber_sentinel.partition_maintenance_log (table_name, partition_name, action, error_message)
                VALUES (rec.table_name, rec.partition_name, 'DROP_FAILED', SQLERRM);
END;
END IF;
END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PART 4: AUTOMATED SCHEDULING (pg_cron — replaces MySQL Event Scheduler)
-- ============================================
-- cron.schedule() upserts by job name on pg_cron >= 1.4 — safe to re-run.
-- Commands are schema-qualified (cyber_sentinel.sp_...) rather than relying
-- on search_path — pg_cron jobs run as whatever role scheduled them
-- (here: postgres, since this script runs as postgres), and postgres's own
-- search_path is not touched by this migration, so qualifying explicitly
-- is the only reliable option.

SELECT cron.schedule(
               'evt_drop_old_partitions',
               '0 2 1 * *',
               'SELECT cyber_sentinel.sp_drop_old_partitions();'
       );

SELECT cron.schedule(
               'evt_add_future_partitions',
               '0 3 1 * *',
               'SELECT cyber_sentinel.sp_add_future_partitions();'
       );

-- ============================================
-- PART 5: UTILITY VIEW (same name as MySQL's v_partition_info)
-- ============================================

CREATE OR REPLACE VIEW cyber_sentinel.v_partition_info AS
SELECT
    parent.relname AS table_name,
    child.relname AS partition_name,
    pg_get_expr(child.relpartbound, child.oid) AS partition_description,
    COALESCE(s.n_live_tup, 0) AS table_rows,
    ROUND(pg_relation_size(child.oid) / 1024.0 / 1024.0, 2) AS data_mb,
    ROUND(pg_indexes_size(child.oid) / 1024.0 / 1024.0, 2) AS index_mb,
    ROUND(pg_total_relation_size(child.oid) / 1024.0 / 1024.0, 2) AS total_mb
FROM pg_inherits i
         JOIN pg_class parent ON parent.oid = i.inhparent
         JOIN pg_class child ON child.oid = i.inhrelid
         JOIN pg_namespace n ON n.oid = parent.relnamespace
         LEFT JOIN pg_stat_user_tables s ON s.relid = child.oid
WHERE n.nspname = 'cyber_sentinel'
  AND parent.relname IN ('dns_queries', 'network_events', 'threat_indicators')
ORDER BY parent.relname, child.relname;

-- ============================================
-- VERIFICATION QUERIES (run manually after deployment)
-- ============================================
-- SELECT * FROM cyber_sentinel.v_partition_info;
-- SELECT * FROM cron.job;                       -- confirm both jobs scheduled
-- SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 20;
-- SELECT * FROM cyber_sentinel.partition_maintenance_log ORDER BY executed_at DESC LIMIT 20;
--
-- Manual trigger for testing:
-- SELECT cyber_sentinel.sp_add_future_partitions();
-- SELECT cyber_sentinel.sp_drop_old_partitions();
-- ============================================