---
- name: 04.3 - Provision HashiCorp Vault Secrets
  hosts: all_servers
  vars:
    vault_url: "http://{{ ansible_host }}:8200"
    services:
      - { name: "pihole" }
      - { name: "n8n" }
      - { name: "portainer" }
      - { name: "firefox" }
      - { name: "grafana" }
      - { name: "hashicorp_vault" }

  tasks:
    - name: Task 1.0 - Wait for Vault to be ready
      ansible.builtin.uri:
        url: "{{ vault_url }}/v1/sys/health"
        status_code: [200, 429]
      retries: 15
      delay: 5

    - name: Task 1.1 - Write VirusTotal Token via REST API
      ansible.builtin.uri:
        url: "{{ vault_url }}/v1/secret/data/cyber-sentinel/api-keys"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_root_token | trim }}"
        body_format: json
        body:
          data:
            vt_token: "{{ vault_virus_total_token }}"
        status_code: [200, 204]
      no_log: true

    - name: Task 1.2 - Write Certificates via REST API
      ansible.builtin.uri:
        url: "{{ vault_url }}/v1/secret/data/cyber-sentinel/certs/{{ item.name }}"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_root_token | trim }}"
        body_format: json
        body:
          data:
            cert: "{{ lookup('vars', 'vault_' + item.name + '_cert') }}"
            key: "{{ lookup('vars', 'vault_' + item.name + '_key') }}"
        status_code: [200, 204]
      loop: "{{ services }}"
      no_log: true

    - name: Task 1.3 - Provision Application Passwords to Vault
      ansible.builtin.uri:
        url: "{{ vault_url }}/v1/secret/data/cyber-sentinel/credentials"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_root_token | trim }}"
        body_format: json
        body:
          data:
            mysql_app_user: "{{ vault_mysql_app_user }}"
            mongodb_password: "{{ vault_mongodb_password }}"
            mysql_password: "{{ vault_mysql_password }}"
            mysql_root_password: "{{ vault_mysql_root_password }}"
            pihole_admin_password: "{{ vault_pihole_admin_password }}"
            grafana_password: "{{ vault_grafana_password }}"
            portainer_password: "{{ vault_portainer_password }}"
            n8n_password: "{{ vault_n8n_password }}"
        status_code: [200, 204]
      no_log: true