---
- name: 05 - Deploy Nginx Reverse Proxy with SSL
  hosts: all
  become: yes
  vars:
    domain_suffix: "{{ 'local' if inventory_hostname in groups['vm-prox-dev'] else 'prod' }}"
    services:
      - { name: "pihole", port: 80, internal_host: "pihole" }
      - { name: "n8n", port: 5678, internal_host: "n8n-server" }
      - { name: "portainer", port: 9000, internal_host: "portainer" }
      - { name: "firefox", port: 3000, internal_host: "firefox" }
      - { name: "grafana", port: 3000, internal_host: "grafana" }
      - { name: "hashicorp_vault", port: 8200, internal_host: "hashicorp_vault" }

  tasks:
    - name: Task 5.0 - Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ deployment_user }}"
        mode: '0755'
      loop:
        - "{{ remote_deploy_base }}/config/nginx/conf.d"
        - "{{ remote_deploy_base }}/config/nginx/certs"

    - name: Task 5.1 - Get Certificates from HashiCorp Vault
      community.hashi_vault.vault_kv2_get:
        url: "http://{{ ansible_host }}:8200"
        token: "{{ vault_root_token }}"
        path: "cyber-sentinel/certs/{{ item.name }}"
      register: vault_certs
      loop: "{{ services }}"
      no_log: true

    - name: Task 5.2 - Save Certificate files (.crt)
      ansible.builtin.copy:
        content: "{{ item.secret.cert }}"
        dest: "{{ remote_deploy_base }}/config/nginx/certs/{{ item.item.name }}.crt"
        owner: "{{ deployment_user }}"
        mode: '0600'
      loop: "{{ vault_certs.results }}"
      no_log: true

    - name: Task 5.3 - Save Private Key files (.key)
      ansible.builtin.copy:
        content: "{{ item.secret.key }}"
        dest: "{{ remote_deploy_base }}/config/nginx/certs/{{ item.item.name }}.key"
        owner: "{{ deployment_user }}"
        mode: '0600'
      loop: "{{ vault_certs.results }}"
      no_log: true

    - name: Task 5.4 - Deploy Nginx Templates
      ansible.builtin.template:
        src: templates/nginx_service.conf.j2
        dest: "{{ remote_deploy_base }}/config/nginx/conf.d/{{ item.name }}.conf"
      loop: "{{ services }}"

    - name: Task 5.5 - Run Nginx Proxy Container
      community.docker.docker_container:
        name: nginx-proxy
        image: nginx:latest
        state: started
        recreate: yes
        restart_policy: always
        networks:
          - name: cyber-sentinel_internal_network
        volumes:
          - "{{ remote_deploy_base }}/config/nginx/conf.d:/etc/nginx/conf.d:ro"
          - "{{ remote_deploy_base }}/config/nginx/certs:/etc/nginx/certs:ro"
        ports:
          - "443:443"
          - "80:80"