apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres_db:5432
    database: cyber_intelligence
    user: hunter
    uid: PCF4C4661FE7E0A44
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    editable: true
